### ISSUE TITLE
Mudar fechamento

### ISSUE THREAD

**Issue by yurikoster1** [yurikoster1/skydive#147]
(https://docs.google.com/spreadsheets/d/1-KpMmXwaNEiABVLQtepREzkyvsaKCtxF6aPBM3fHLCM/edit#gid=0)

resumo:					
					
					
					
					
					
					
Debito	Listar pessoas com pacotes < 0 || R$ acordo >0 || gratis < 0 && group == false				
Nome	Pacote	Acordo	Debito Retroativo	Credito	Total
nome/carteira	pacote negATIVO	R$ acordo	(Debito-R$ Acordo)-Credito	Credito	"TOtal colunas
"
					
Pacotes:	List pessoas com saltos tipo Pacote && com pacote > 0 && group == false				
Nome	Saltos	Retroativo	Saldo Atual		
nome/carteira	Saltos tipo pacote em manisfesto	Pacote	Pacote - Saltos tipo pacote em manisfesto		
					
Gratis:	List  pessoas com saltos tipo gratis && com gratis > 0 && group == false				
Nome	Saltos	Retroativo	Saldo Atual		
nome/carteira	Saltos tipo Gratis em manisfesto	Free	Free - Saltos tipo gratis em manisfesto		
					
Grupos	List pessoas group == true				
Carteira	Saltos	"Debito
"			
nome/carteira	"Salto tipo pacote em manifesto
"	B2 * pacote carteira

**Comment by jfmescolotti** [comment]
Man vi aqui que fechou vários issues, já upou?

**Comment by yurikoster1** [comment]
falta colunas
