### ISSUE TITLE
Gerenciador de clientes

### ISSUE THREAD

**Issue by jfmescolotti** [yurikoster1/skydive#25]
Alterar Gerenciador de clientes para Cadastro de Atletas

Na principal alterar "Nivel" para "Categoria"
Topo dos menus colocar nome em cima de "cadastro" e "Vendas"

**Comment by yurikoster1** [comment]
feito em 6328512be332a7c819c2ddabf6a6129efdbfd440 e 3fd2702985b1153af8c6d8be57dd47552b1dc567
