### ISSUE TITLE
Página Login

### ISSUE THREAD

**Issue by nuneswagner22** [yurikoster1/skydive#66]
Login:
- se eu erro o login ou a senha, a resposta que recebo é em inglês. Colocar em português.

Cadastro cliente:
- botão de pesquisar cep não está funcionando.
- Na parte final do cadastro existe um item para escolha de "individuo ou grupo" que não funciona.

Clientes:
- Quando clico no botão carteiras as vezes ele abre sem as informações do usuário preenchidas.

Gerenciar decolagem:
- No modal de cancelamento de decolagem precisa trocar a frase "cancelar voo" por "cancelar decolagem". E no texto onde está "decolagem 16", deveria ser "ID 16".
- Quando seleciono um cliente e tento alterar o tipo de pagamento do salto, fica aparecendo um modal com "true". Retirar esse modal.

**Comment by yurikoster1** [comment]
Quando clico no botão carteiras as vezes ele abre sem as informações do usuário preenchidas.

Não consegui reproduzir. em que cliente acontece o bug?

**Comment by yurikoster1** [comment]
botão de pesquisar cep não está funcionando. duplicata de #64

**Comment by yurikoster1** [comment]
Na parte final do cadastro existe um item para escolha de "individuo ou grupo" que não funciona.

issue separado em #71
