### ISSUE TITLE
Manifesto - adição de atletas não cadastrados

### ISSUE THREAD

**Issue by nuneswagner22** [yurikoster1/skydive#83]
Após receber a mensagem de alerta informando que alguns atletas não estavam cadastrados, aparece a opção para cadastrar esses atletas um por vez (o que é legal, foi uma das alterações solicitadas ). Porem quando cliquei para cadastrar um desses atletas fui levado para a página de cadastro de atletas, ao finalizar o cadastro dele e retornar para o manifesto os outros atletas que faltava cadastrar sumiram do manifesto.

Precisa ser feito de uma maneira que após eu cadastrar esse atleta, eu já volte para a mesma página do manifesto com as informações cadastradas anteriormente salvas e a possibilidade de cadastrar os outros atletas que também não estavam cadastrados.

![alerta](https://cloud.githubusercontent.com/assets/1125657/8092067/d421c7b4-0f8d-11e5-9ac6-d0ee2a349f81.png)

![alerta 2](https://cloud.githubusercontent.com/assets/1125657/8092118/12ff0c9e-0f8e-11e5-82fe-399142a82419.png)

**Comment by yurikoster1** [comment]
o que é possível é abrir as paginas de cadastro em uma nova janela. entao apos o cadastro o usuario fecha a nova aba e volta para o manifesto

**Comment by yurikoster1** [comment]
implementado, Falta CSS para novo Botão OK desenhado na figura 2

**Comment by nuneswagner22** [comment]
Blz!
