### ISSUE TITLE
Manifesto - Finalização de cadastro de decolagem

### ISSUE THREAD

**Issue by nuneswagner22** [yurikoster1/skydive#84]
Ao terminar o cadastro dos atletas e finalizar o manifesto, cliquei em finalizar voo
e tudo desapareceu. É melhor essa opção ficar apenas em fechamento pra isso não acontecer durante a operação. Essas informações podem ser necessários ao longo do dia e não podem sumir.

**Comment by yurikoster1** [comment]
Existe a opção de visualizar decolagens finalizadas. Talvez vocês queriam que essa opção esteja ativada por padrão? 
![fig1](https://cloud.githubusercontent.com/assets/2926881/8092863/501f6128-0f93-11e5-9573-2094cbdbadbe.png)
<b>Escondidos</b>
![fig2](https://cloud.githubusercontent.com/assets/2926881/8092865/53b0840c-0f93-11e5-9a6f-8ae89e0e9beb.png)
<b>Mostrados</b>

**Comment by nuneswagner22** [comment]
Deixar ativa por padrão.
